# Generated by Django 4.2.7 on 2023-11-08 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0002_post_post_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_img",
            field=models.ImageField(blank=True, null=True, upload_to="images/"),
        ),
    ]
