# Generated by Django 4.2.7 on 2023-11-08 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0003_post_post_img"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post", old_name="post_img", new_name="post_image",
        ),
    ]
