# Generated by Django 4.2.7 on 2023-11-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0004_rename_post_img_post_post_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="post_video",
            field=models.FileField(blank=True, null=True, upload_to="videos"),
        ),
    ]
