# Generated by Django 4.2.7 on 2023-11-09 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0005_post_post_video"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="update_date",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
