# Generated by Django 4.2.7 on 2023-11-09 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0006_post_update_date_alter_post_post_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="update_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
