# Generated by Django 4.2.7 on 2023-11-09 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ourblog", "0007_alter_post_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="update_date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
